import { useState } from 'react'
import { SliderEventData } from '@boxslider/slider'
import { CubeSlider } from '@boxslider/react'
import './App.css'

function App() {
  const [slideIndex, setSlideIndex] = useState(0)
  const [activeIndex, setActiveIndex] = useState(0)
  const images = Array.from({ length: 6 }).map(
    (n, i) => `/Futuristic_city_scape_on_a_distant_alien_planet_${i + 1}.png`,
  )

  return (
    <div className="App">
      <header>
        <h1>Box Slider</h1>
      </header>

      <main>
        <section className="slider-viewport" aria-roledescription="carousel">
          <CubeSlider
            id="slider"
            className="slider"
            aria-label="Image carousel"
            effectOptions={{ direction: 'vertical' }}
            onAfter={(ev: SliderEventData) => setActiveIndex(ev.currentIndex)}
            slideIndex={slideIndex}>
            {images.map((image, i) => (
              <div key={image} className="slide">
                <img src={image} alt={`Image ${i + 1} of ${images.length} generated by Stable Diffusion`} />
              </div>
            ))}
          </CubeSlider>
        </section>

        <section className="slider-controls">
          {images.map((image, i) => (
            <button
              key={image}
              aria-controls="slider"
              className={`show-slide-btn${i === activeIndex ? ' active' : ''}`}
              aria-label={`Show slide ${i}`}
              onClick={() => setSlideIndex(i)}
            />
          ))}
        </section>
      </main>

      <footer>
        <p>Images of “Futuristic city scape on a distant alien planet” created with Stable Diffusion</p>
      </footer>
    </div>
  )
}

export default App
